// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVKH-y09R3b1T74ZU_t2YS7qNmgHBl8UU',
    appId: '1:136477109824:web:f95bd68da0cf86a923b9a5',
    messagingSenderId: '136477109824',
    projectId: 'confesi-server-dev',
    authDomain: 'confesi-server-dev.firebaseapp.com',
    storageBucket: 'confesi-server-dev.appspot.com',
    measurementId: 'G-CXZP5RE27J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuW_NNrzhaQ5M4TjhxVSz6LgeNJRAQuQk',
    appId: '1:136477109824:android:db0a1b5d644cfa7c23b9a5',
    messagingSenderId: '136477109824',
    projectId: 'confesi-server-dev',
    storageBucket: 'confesi-server-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu0pfSj4Sb_TvbTETfgwt22FS21Es0YNI',
    appId: '1:136477109824:ios:74f41d419b8f6e9423b9a5',
    messagingSenderId: '136477109824',
    projectId: 'confesi-server-dev',
    storageBucket: 'confesi-server-dev.appspot.com',
    iosClientId: '136477109824-72l0bmk336r530cno1gs9cn8dmrgdf4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMobileClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu0pfSj4Sb_TvbTETfgwt22FS21Es0YNI',
    appId: '1:136477109824:ios:74f41d419b8f6e9423b9a5',
    messagingSenderId: '136477109824',
    projectId: 'confesi-server-dev',
    storageBucket: 'confesi-server-dev.appspot.com',
    iosClientId: '136477109824-72l0bmk336r530cno1gs9cn8dmrgdf4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMobileClient',
  );
}
